### ISSUE TITLE
What's the default admin username and password?

### ISSUE THREAD

**Issue by fishfree** [avalonmediasystem/avalon-docker#63]
After running `docker-composer up -d`, I can access Avalon web UI. I registered the first user account, which seemed not to be the admin user. So what's the default admin username, password and admin path? If there is none, how to create the admin user?
I'm a novice to Avalon. I searched all the docs, but no luck. Thanks!

**Comment by fishfree** [comment]
Here is the [guide](https://github.com/avalonmediasystem/avalon/README.md).

**Comment by NumerousHats** [comment]
I'm sorry, where is this information? The link above is broken.

I looked at the various READMEs and couldn't find any answer to this question (which I also have).

**Comment by cjcolvar** [comment]
Because the `docker-compose` file runs avalon in a production environment there isn't a default user/password.  There are two ways to handle this:

1. Set the `SETTINGS__INITIAL_USER` environment variable in the avalon container's environment in `docker-compose.yml`, restart the avalon container, then create an account in using that email address.  (See https://github.com/avalonmediasystem/avalon/blob/master/config/role_map.yml#L23)
2. Go into the avalon container and run the `avalon:user:admin` rake task to assign admin abilities to an existing user:
```
docker exec -it avalondocker_avalon_1 /bin/bash
$ bundle exec rake avalon:user:admin
```
